apiVersion: v1
kind: ConfigMap
metadata:
  name: metabase-config
  namespace: demo
data:
  MB_DB_TYPE: postgres
  MB_DB_DBNAME: metabase
  MB_DB_PORT: '5432'
  MB_DB_USER: postgres
  MB_DB_PASS: postgres
  MB_DB_HOST: {{.Values.rds_hostname}}
