connector:
  name: github50
  identifier: github50
  description:
  orgIdentifier: default
  projectIdentifier: ngdemo
  type: Github
  spec:
    url: https://github.com/venkat50
    validationRepo: hello-world
    authentication:
      type: Http
      spec:
        type: UsernameToken
        spec:
          username: venkat50
          tokenRef: account.github50pat
    apiAccess:
      type: Token
      spec:
        tokenRef: account.github50pat
    delegateSelectors:
    - ng
    executeOnDelegate: true
    type: Account
