apiVersion: v1 
kind: Service 
metadata: 
  name: harness-cv-prom-example-service
spec:
  selector:
    app: harness-cv-prom-example
  ports:
    - protocol: "TCP"
      port: 8082 
      targetPort: 8082 
