apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: guestbook
spec:
  generators:
  - git:
      repoURL: https://github.com/venkat50/harness-ng.git
      revision: HEAD
      files:
      - path: "kustomize/cluster-config/**/config.json"
  template:
    metadata:
      annotations:
        notifications.argoproj.io/subscribe.out-of-sync.harness: ""
      name: '{{cluster_name}}-guestbook'
      labels:
        harness.io/envRef: '{{environment}}'
        harness.io/serviceRef: '{{harness_service}}'
        harness.io/buildRef: '{{image_tag}}'
    spec:
      project: bd0e5225
      source:
        repoURL: https://github.com/venkat50/harness-ng.git
        targetRevision: HEAD
        path: kustomize/apps
        kustomize:
          namePrefix: '{{environment}}-'
          images:
            - 'mansong/guestbook:{{image_tag}}'
      destination:
        server: '{{server_address}}'
        namespace: 'guestbook-{{environment}}'
      syncPolicy:
        syncOptions:
        - PrunePropagationPolicy=foreground
        - PruneLast=true
        - CreateNamespace=true
        - ApplyOutOfSyncOnly=true
        - Replace=true
